export const MAIN_URL = "https://api.candivet.com";

export const API_CONFIG = {
  REGISTER_USER: `${MAIN_URL}/auth/user-register/`,
  VERIFY_EMAIL: `${MAIN_URL}/auth/verify-account/`,
  LOGIN_USER: `${MAIN_URL}/auth/login/`,
  LOGIN_USER_GOOGLE: `${MAIN_URL}/auth/google/`,
  FORGOT_PASSWORD: `${MAIN_URL}/auth/request-password-reset/`,
  RESET_PASSWORD: `${MAIN_URL}/auth/confirm-password-reset/`,
  CREATE_JOB: `${MAIN_URL}/job/create-job/`,
  TRANSLATE_JOB_POSTING: `${MAIN_URL}/job/translate-jp/`,
  SUMMARIZE_CV: `${MAIN_URL}/cv/summarize-cv/`,
  TRANSLATE_CV: `${MAIN_URL}/cv/translate-cv/`,
  REWRITE_CV: `${MAIN_URL}/cv/rewrite-cv/`,
  VET_CV: `${MAIN_URL}/cv/vetting-cv/`,
  HEAD_TO_HEAD: `${MAIN_URL}/cv/head-to-head/`,
  GENERATE_CV: `${MAIN_URL}/cv/generate-cv/`,
  RANK_CV: `${MAIN_URL}/cv/rank-cv/`,
  SUMMARIZE_COVER_LETTER: `${MAIN_URL}/cl/summarize-cl/`,
  VET_COVER_LETTER: `${MAIN_URL}/cl/vett-cl/`,
  RANK_COVER_LETTER: `${MAIN_URL}/cl/rank-cl/`,
  GENERATE_COVER_LETTER: `${MAIN_URL}/cl/generate-cl/`,
  TRANSLATE_COVER_LETTER: `${MAIN_URL}/cl/translate-cl/`,
  REWRITE_COVER_LETTER: `${MAIN_URL}/cl/rewrite-cl/`,
  GENERATE_JOB: `${MAIN_URL}/job/create-job-with-ai/`,
  VET_JOB: `${MAIN_URL}/job/vet-job-post/`,
  INTERVIEW_QUESTION_GEN: `${MAIN_URL}/job/interview-questions-gen/`,
  SCREEN_INTERVIEW_QUESTION: `${MAIN_URL}/job/screen-interview-questions/`,
  GET_CANDIDATE_REPORT: `${MAIN_URL}/job/get-candidate-report/`,
  GET_JOB_OPENINGS: `${MAIN_URL}/job/get-jobs/`,

  GET_DASHBOARD_STATS: `${MAIN_URL}/job/dashboard-stats/`,
  BULK_ACTION: `${MAIN_URL}/job/bulk-update-jobs/`,
  JOB_APPLICATIONS: `${MAIN_URL}/job/get-applications/`,
  JOB_DETAIL: `${MAIN_URL}/job/get-job-item/`,
  SUBMIT_JOB_APPLICATION: `${MAIN_URL}/job/submit-application/`,
  GET_JOB_APPLICATION_ITEM: `${MAIN_URL}/job/get-application-item/{application_id}/`,
  GET_JOB_OPEN: `${MAIN_URL}/job/get-jobs-open/`,
  SUBMIT_ARTICLE: `${MAIN_URL}/job/submit-article/`,
  UPDATE_PROFILE: `${MAIN_URL}/profile/update-profile/`,
  UPDATE_SETTINGS: `${MAIN_URL}/profile/update-settings/`,
  GET_PROFILE_SETTINGS: `${MAIN_URL}/profile/get-settings/`,
  ADD_TEAM_MEMBER: `${MAIN_URL}/profile/add-team-member/`,
  GET_TEAM_MEMBERS: `${MAIN_URL}/profile/get-member/`,
  GET_TEAMS: `${MAIN_URL}/profile/get-teams/`,
  FEEDBACK_SUPPORT: `${MAIN_URL}/profile/submit-feedback/`,

  GET_TALENTS: (page: number) => `${MAIN_URL}/talent/get-talents/${page}/`,
  GET_TALENT_ITEM: (talent_id: string) =>
    `${MAIN_URL}/talent/get-talent-item/${talent_id}/`,
  TALENT_START_CHAT: (talent_id: string) =>
    `${MAIN_URL}/talent/start-chat/${talent_id}/`,
  TALENT_DELETE_CHAT: (channel_id: string) =>
    `${MAIN_URL}/talent/delete-chat/${channel_id}/`,
  TALENT_GET_CHATS: `${MAIN_URL}/talent/get-chats/`,
};
