export interface Country {
  name: string;
  nationality: string;
  code: string;
}

export const countries: Country[] = [
  { name: "Afghanistan", nationality: "Afghan", code: "AF" },
  { name: "Albania", nationality: "Albanian", code: "AL" },
  { name: "Algeria", nationality: "Algerian", code: "DZ" },
  { name: "Andorra", nationality: "Andorran", code: "AD" },
  { name: "Angola", nationality: "Angolan", code: "AO" },
  { name: "Antigua and Barbuda", nationality: "Antiguan", code: "AG" },
  { name: "Argentina", nationality: "Argentine", code: "AR" },
  { name: "Armenia", nationality: "Armenian", code: "AM" },
  { name: "Australia", nationality: "Australian", code: "AU" },
  { name: "Austria", nationality: "Austrian", code: "AT" },
  { name: "Azerbaijan", nationality: "Azerbaijani", code: "AZ" },
  { name: "Bahamas", nationality: "Bahamian", code: "BS" },
  { name: "Bahrain", nationality: "Bahraini", code: "BH" },
  { name: "Bangladesh", nationality: "Bangladeshi", code: "BD" },
  { name: "Barbados", nationality: "Barbadian", code: "BB" },
  { name: "Belarus", nationality: "Belarusian", code: "BY" },
  { name: "Belgium", nationality: "Belgian", code: "BE" },
  { name: "Belize", nationality: "Belizean", code: "BZ" },
  { name: "Benin", nationality: "Beninese", code: "BJ" },
  { name: "Bhutan", nationality: "Bhutanese", code: "BT" },
  { name: "Bolivia", nationality: "Bolivian", code: "BO" },
  { name: "Bosnia and Herzegovina", nationality: "Bosnian", code: "BA" },
  { name: "Botswana", nationality: "Motswana", code: "BW" },
  { name: "Brazil", nationality: "Brazilian", code: "BR" },
  { name: "Brunei", nationality: "Bruneian", code: "BN" },
  { name: "Bulgaria", nationality: "Bulgarian", code: "BG" },
  { name: "Burkina Faso", nationality: "Burkinabe", code: "BF" },
  { name: "Burundi", nationality: "Burundian", code: "BI" },
  { name: "Cambodia", nationality: "Cambodian", code: "KH" },
  { name: "Cameroon", nationality: "Cameroonian", code: "CM" },
  { name: "Canada", nationality: "Canadian", code: "CA" },
  { name: "Cape Verde", nationality: "Cape Verdean", code: "CV" },
  {
    name: "Central African Republic",
    nationality: "Central African",
    code: "CF",
  },
  { name: "Chad", nationality: "Chadian", code: "TD" },
  { name: "Chile", nationality: "Chilean", code: "CL" },
  { name: "China", nationality: "Chinese", code: "CN" },
  { name: "Colombia", nationality: "Colombian", code: "CO" },
  { name: "Comoros", nationality: "Comoran", code: "KM" },
  { name: "Congo", nationality: "Congolese", code: "CG" },
  { name: "Costa Rica", nationality: "Costa Rican", code: "CR" },
  { name: "Croatia", nationality: "Croatian", code: "HR" },
  { name: "Cuba", nationality: "Cuban", code: "CU" },
  { name: "Cyprus", nationality: "Cypriot", code: "CY" },
  { name: "Czech Republic", nationality: "Czech", code: "CZ" },
  { name: "Denmark", nationality: "Danish", code: "DK" },
  { name: "Djibouti", nationality: "Djibouti", code: "DJ" },
  { name: "Dominica", nationality: "Dominican", code: "DM" },
  { name: "Dominican Republic", nationality: "Dominican", code: "DO" },
  { name: "East Timor", nationality: "East Timorese", code: "TL" },
  { name: "Ecuador", nationality: "Ecuadorian", code: "EC" },
  { name: "Egypt", nationality: "Egyptian", code: "EG" },
  { name: "El Salvador", nationality: "Salvadoran", code: "SV" },
  { name: "Equatorial Guinea", nationality: "Equatorial Guinean", code: "GQ" },
  { name: "Eritrea", nationality: "Eritrean", code: "ER" },
  { name: "Estonia", nationality: "Estonian", code: "EE" },
  { name: "Ethiopia", nationality: "Ethiopian", code: "ET" },
  { name: "Fiji", nationality: "Fijian", code: "FJ" },
  { name: "Finland", nationality: "Finnish", code: "FI" },
  { name: "France", nationality: "French", code: "FR" },
  { name: "Gabon", nationality: "Gabonese", code: "GA" },
  { name: "Gambia", nationality: "Gambian", code: "GM" },
  { name: "Georgia", nationality: "Georgian", code: "GE" },
  { name: "Germany", nationality: "German", code: "DE" },
  { name: "Ghana", nationality: "Ghanaian", code: "GH" },
  { name: "Greece", nationality: "Greek", code: "GR" },
  { name: "Grenada", nationality: "Grenadian", code: "GD" },
  { name: "Guatemala", nationality: "Guatemalan", code: "GT" },
  { name: "Guinea", nationality: "Guinean", code: "GN" },
  { name: "Guinea-Bissau", nationality: "Guinea-Bissauan", code: "GW" },
  { name: "Guyana", nationality: "Guyanese", code: "GY" },
  { name: "Haiti", nationality: "Haitian", code: "HT" },
  { name: "Honduras", nationality: "Honduran", code: "HN" },
  { name: "Hungary", nationality: "Hungarian", code: "HU" },
  { name: "Iceland", nationality: "Icelandic", code: "IS" },
  { name: "India", nationality: "Indian", code: "IN" },
  { name: "Indonesia", nationality: "Indonesian", code: "ID" },
  { name: "Iran", nationality: "Iranian", code: "IR" },
  { name: "Iraq", nationality: "Iraqi", code: "IQ" },
  { name: "Ireland", nationality: "Irish", code: "IE" },
  { name: "Israel", nationality: "Israeli", code: "IL" },
  { name: "Italy", nationality: "Italian", code: "IT" },
  { name: "Jamaica", nationality: "Jamaican", code: "JM" },
  { name: "Japan", nationality: "Japanese", code: "JP" },
  { name: "Jordan", nationality: "Jordanian", code: "JO" },
  { name: "Kazakhstan", nationality: "Kazakhstani", code: "KZ" },
  { name: "Kenya", nationality: "Kenyan", code: "KE" },
  { name: "Kiribati", nationality: "I-Kiribati", code: "KI" },
  { name: "Korea, North", nationality: "North Korean", code: "KP" },
  { name: "Korea, South", nationality: "South Korean", code: "KR" },
  { name: "Kuwait", nationality: "Kuwaiti", code: "KW" },
  { name: "Kyrgyzstan", nationality: "Kyrgyzstani", code: "KG" },
  { name: "Laos", nationality: "Laotian", code: "LA" },
  { name: "Latvia", nationality: "Latvian", code: "LV" },
  { name: "Lebanon", nationality: "Lebanese", code: "LB" },
  { name: "Lesotho", nationality: "Mosotho", code: "LS" },
  { name: "Liberia", nationality: "Liberian", code: "LR" },
  { name: "Libya", nationality: "Libyan", code: "LY" },
  { name: "Liechtenstein", nationality: "Liechtensteiner", code: "LI" },
  { name: "Lithuania", nationality: "Lithuanian", code: "LT" },
  { name: "Luxembourg", nationality: "Luxembourger", code: "LU" },
  { name: "Madagascar", nationality: "Malagasy", code: "MG" },
  { name: "Malawi", nationality: "Malawian", code: "MW" },
  { name: "Malaysia", nationality: "Malaysian", code: "MY" },
  { name: "Maldives", nationality: "Maldivan", code: "MV" },
  { name: "Mali", nationality: "Malian", code: "ML" },
  { name: "Malta", nationality: "Maltese", code: "MT" },
  { name: "Marshall Islands", nationality: "Marshallese", code: "MH" },
  { name: "Mauritania", nationality: "Mauritanian", code: "MR" },
  { name: "Mauritius", nationality: "Mauritian", code: "MU" },
  { name: "Mexico", nationality: "Mexican", code: "MX" },
  { name: "Micronesia", nationality: "Micronesian", code: "FM" },
  { name: "Moldova", nationality: "Moldovan", code: "MD" },
  { name: "Monaco", nationality: "Monacan", code: "MC" },
  { name: "Mongolia", nationality: "Mongolian", code: "MN" },
  { name: "Morocco", nationality: "Moroccan", code: "MA" },
  { name: "Mozambique", nationality: "Mozambican", code: "MZ" },
  { name: "Myanmar", nationality: "Myanmar", code: "MM" },
  { name: "Namibia", nationality: "Namibian", code: "NA" },
  { name: "Nauru", nationality: "Nauruan", code: "NR" },
  { name: "Nepal", nationality: "Nepalese", code: "NP" },
  { name: "Netherlands", nationality: "Dutch", code: "NL" },
  { name: "New Zealand", nationality: "New Zealander", code: "NZ" },
  { name: "Nicaragua", nationality: "Nicaraguan", code: "NI" },
  { name: "Niger", nationality: "Nigerien", code: "NE" },
  { name: "Nigeria", nationality: "Nigerian", code: "NG" },
  { name: "Norway", nationality: "Norwegian", code: "NO" },
  { name: "Oman", nationality: "Omani", code: "OM" },
  { name: "Pakistan", nationality: "Pakistani", code: "PK" },
  { name: "Palau", nationality: "Palauan", code: "PW" },
  { name: "Panama", nationality: "Panamanian", code: "PA" },
  { name: "Papua New Guinea", nationality: "Papua New Guinean", code: "PG" },
  { name: "Paraguay", nationality: "Paraguayan", code: "PY" },
  { name: "Peru", nationality: "Peruvian", code: "PE" },
  { name: "Philippines", nationality: "Filipino", code: "PH" },
  { name: "Poland", nationality: "Polish", code: "PL" },
  { name: "Portugal", nationality: "Portuguese", code: "PT" },
  { name: "Qatar", nationality: "Qatari", code: "QA" },
  { name: "Romania", nationality: "Romanian", code: "RO" },
  { name: "Russia", nationality: "Russian", code: "RU" },
  { name: "Rwanda", nationality: "Rwandan", code: "RW" },
  {
    name: "Saint Kitts and Nevis",
    nationality: "Kittian and Nevisian",
    code: "KN",
  },
  { name: "Saint Lucia", nationality: "Saint Lucian", code: "LC" },
  { name: "Saint Vincent", nationality: "Saint Vincentian", code: "VC" },
  { name: "Samoa", nationality: "Samoan", code: "WS" },
  { name: "San Marino", nationality: "San Marinese", code: "SM" },
  { name: "Sao Tome and Principe", nationality: "Sao Tomean", code: "ST" },
  { name: "Saudi Arabia", nationality: "Saudi", code: "SA" },
  { name: "Senegal", nationality: "Senegalese", code: "SN" },
  { name: "Serbia", nationality: "Serbian", code: "RS" },
  { name: "Seychelles", nationality: "Seychellois", code: "SC" },
  { name: "Sierra Leone", nationality: "Sierra Leonean", code: "SL" },
  { name: "Singapore", nationality: "Singaporean", code: "SG" },
  { name: "Slovakia", nationality: "Slovak", code: "SK" },
  { name: "Slovenia", nationality: "Slovenian", code: "SI" },
  { name: "Solomon Islands", nationality: "Solomon Islander", code: "SB" },
  { name: "Somalia", nationality: "Somali", code: "SO" },
  { name: "South Africa", nationality: "South African", code: "ZA" },
  { name: "South Sudan", nationality: "South Sudanese", code: "SS" },
  { name: "Spain", nationality: "Spanish", code: "ES" },
  { name: "Sri Lanka", nationality: "Sri Lankan", code: "LK" },
  { name: "Sudan", nationality: "Sudanese", code: "SD" },
  { name: "Suriname", nationality: "Surinamer", code: "SR" },
  { name: "Swaziland", nationality: "Swazi", code: "SZ" },
  { name: "Sweden", nationality: "Swedish", code: "SE" },
  { name: "Switzerland", nationality: "Swiss", code: "CH" },
  { name: "Syria", nationality: "Syrian", code: "SY" },
  { name: "Taiwan", nationality: "Taiwanese", code: "TW" },
  { name: "Tajikistan", nationality: "Tajikistani", code: "TJ" },
  { name: "Tanzania", nationality: "Tanzanian", code: "TZ" },
  { name: "Thailand", nationality: "Thai", code: "TH" },
  { name: "Togo", nationality: "Togolese", code: "TG" },
  { name: "Tonga", nationality: "Tongan", code: "TO" },
  {
    name: "Trinidad and Tobago",
    nationality: "Trinidadian or Tobagonian",
    code: "TT",
  },
  { name: "Tunisia", nationality: "Tunisian", code: "TN" },
  { name: "Turkey", nationality: "Turkish", code: "TR" },
  { name: "Turkmenistan", nationality: "Turkmen", code: "TM" },
  { name: "Tuvalu", nationality: "Tuvaluan", code: "TV" },
  { name: "Uganda", nationality: "Ugandan", code: "UG" },
  { name: "Ukraine", nationality: "Ukrainian", code: "UA" },
  { name: "United Arab Emirates", nationality: "Emirian", code: "AE" },
  { name: "United Kingdom", nationality: "British", code: "GB" },
  { name: "United States", nationality: "American", code: "US" },
  { name: "Uruguay", nationality: "Uruguayan", code: "UY" },
  { name: "Uzbekistan", nationality: "Uzbekistani", code: "UZ" },
  { name: "Vanuatu", nationality: "Ni-Vanuatu", code: "VU" },
  { name: "Vatican City", nationality: "Vatican", code: "VA" },
  { name: "Venezuela", nationality: "Venezuelan", code: "VE" },
  { name: "Vietnam", nationality: "Vietnamese", code: "VN" },
  { name: "Yemen", nationality: "Yemeni", code: "YE" },
  { name: "Zambia", nationality: "Zambian", code: "ZM" },
  { name: "Zimbabwe", nationality: "Zimbabwean", code: "ZW" },
];
